package DSS;

import java.awt.Color;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author L - Arch
 */
public class MainDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashBoard
     */
    public MainDashBoard() {
        initComponents();
         this.setBackground (new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        adminLogin = new javax.swing.JButton();
        managerLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize);
        Minimize.setBounds(1125, 6, 25, 25);

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(1161, 6, 25, 25);

        adminLogin.setBackground(new java.awt.Color(255, 255, 255));
        adminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DSS/image/Ad Login D.png"))); // NOI18N
        adminLogin.setBorderPainted(false);
        adminLogin.setContentAreaFilled(false);
        adminLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/DSS/image/Ad Login L.png"))); // NOI18N
        adminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLoginMouseClicked(evt);
            }
        });
        adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(adminLogin);
        adminLogin.setBounds(850, 370, 191, 46);

        managerLogin.setBackground(new java.awt.Color(255, 255, 255));
        managerLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DSS/image/M Login D.png"))); // NOI18N
        managerLogin.setBorderPainted(false);
        managerLogin.setContentAreaFilled(false);
        managerLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/DSS/image/M Login L.png"))); // NOI18N
        managerLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerLoginMouseClicked(evt);
            }
        });
        managerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLoginActionPerformed(evt);
            }
        });
        getContentPane().add(managerLogin);
        managerLogin.setBounds(912, 410, 198, 46);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1208, 40);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DSS/image/DP Main_Manu.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1208, 608);

        setSize(new java.awt.Dimension(1208, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

      int kordinatX = evt.getXOnScreen();
      int kordinatY = evt.getYOnScreen();
      
      this.setLocation(kordinatX-604,kordinatY-21);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        
        this.setState(this.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginActionPerformed
        
    }//GEN-LAST:event_adminLoginActionPerformed

    private void managerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerLoginActionPerformed

    private void adminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLoginMouseClicked
        
        adminLogin al = new adminLogin();
        al.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLoginMouseClicked

    private void managerLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerLoginMouseClicked
        
        managerLogin ml = new managerLogin();
        ml.setVisible(true);
        this.setVisible(false);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_managerLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Minimize;
    private javax.swing.JButton adminLogin;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton managerLogin;
    // End of variables declaration//GEN-END:variables
}
